Removal of files option of the cli + dep upgrade + cs
rust-db/refinery pull request #175
Opened 2021-09-13 09:51 UTC by omid

Fixes #174

2021-09-15 09:30 UTC, jxs requested changes
Thanks for this. There are still refferences to the [`files` subcommand](https://github.com/omid/refinery/blob/remove_files_from_cli/refinery_cli/src/migrate.rs#L15-L26) and the cli tests still use it also, that's why they are failing.   
Due to what we discussed on #170 it probably doesn't make sense to support `.rs` migration files here, so we should introduce differentiation between just `.sql` files and both of them similar to what [we had here](https://github.com/rust-db/refinery/blob/cc0ad88469ecdff8f10b2a96e84ea8c5432d04b5/refinery_core/src/util.rs#L10-L24) to be called on just `.sql` files for the `cli` case, sorry I missed it on #170. 
What do you think?

2021-09-17 14:19 UTC, omid commented
How come I forgot to touch the logic :D stupid me.

Anyway, about what you said. Sorry, I didn't get it, why should we only run `.sql` files with CLI? Or you mean something else?

2021-09-17 15:11 UTC, omid commented
OK, I think I understood what you mean. We should add thee `rs` support to cli. I'm on it.

2021-09-18 10:30 UTC, jxs commented
Hi, no worries :grinning: meanwhile I have addressed that issue while working on #177, see https://github.com/jxs/refinery/pull/177/commits/fa28ffc2ec42fb76a76e1beddb882eea5ce8497f and feel free to rebase against `main`

2021-09-18 11:10 UTC, jxs approved these changes
LGTM thanks! :fireworks:

2021-09-18 11:10 UTC, jxs commented on refinery_cli/src/migrate.rs
> +    path: &str,
thanks for this improvement :ok_hand:

2021-09-18 11:11 UTC, merged

2021-09-18 11:20 UTC, omid commented
OK, cool 👍🏼